#!/usr/bin/env python3
"""Generate the complete, synthetic company.json reference fixture."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


AS_OF = "2026-08-20"


def evidence(
    title: str,
    url: str,
    publisher: str,
    source_type: str,
    locator: str,
    excerpt: str,
    note: str,
    scope: list[str],
) -> dict[str, Any]:
    return {
        "sourceTitle": title,
        "sourceUrl": url,
        "publisher": publisher,
        "sourceType": source_type,
        "publishedOn": "2026-08-01",
        "retrievedOn": AS_OF,
        "locator": locator,
        "excerpt": excerpt,
        "note": note,
        "verificationScope": scope,
    }


def official(locator: str, excerpt: str, note: str, scope: list[str]) -> dict[str, Any]:
    return evidence(
        "Example Build Systems official profile",
        "https://example.com/company-profile",
        "Example Build Systems Ltd.",
        "official_website",
        locator,
        excerpt,
        note,
        scope,
    )


def project_evidence(locator: str, excerpt: str, note: str, scope: list[str]) -> dict[str, Any]:
    return evidence(
        "Harbour Residence project page",
        "https://example.com/projects/harbour-residence",
        "Example Build Systems Ltd.",
        "official_website",
        locator,
        excerpt,
        note,
        scope,
    )


def inquiry_evidence(locator: str, excerpt: str, note: str, scope: list[str]) -> dict[str, Any]:
    return evidence(
        "Inquiry WEB-2026-001 and technical attachment",
        "https://example.com/customer-documents/WEB-2026-001",
        "Example Developments Pty Ltd.",
        "customer_document",
        locator,
        excerpt,
        note,
        scope,
    )


def dimension(
    code: str,
    name: str,
    observed: float,
    baseline: float,
    final: float,
    maximum: int,
    level: str,
    rationale: str,
    source: dict[str, Any],
    gap: str,
    cap: str,
) -> dict[str, Any]:
    return {
        "dimensionCode": code,
        "name": name,
        "observedScore": observed,
        "baselineScore": baseline,
        "baselinePolicy": "Same-country, same-role cohort median as of 2026-08-20.",
        "finalDimensionScore": final,
        "maxScore": maximum,
        "evidenceGrade": "A",
        "evidenceWeight": 1.0,
        "level": level,
        "rationale": rationale,
        "evidence": [source],
        "gapCodes": [gap],
        "capCodes": [cap],
    }


def inquiry_dimension(
    code: str,
    name: str,
    score: int,
    maximum: int,
    rationale: str,
    source: dict[str, Any],
    gap: str,
) -> dict[str, Any]:
    return {
        "dimensionCode": code,
        "name": name,
        "score": score,
        "maxScore": maximum,
        "rationale": rationale,
        "evidence": [source],
        "gapCodes": [gap],
    }


def build_example() -> dict[str, Any]:
    registry = evidence(
        "Example Registry extract",
        "https://registry.example/companies/123456789",
        "Example Corporate Registry",
        "registry",
        "Registration 123456789",
        "Example Build Systems Ltd. is active and registered in Australia.",
        "Synthetic strong identity anchor for the reference fixture.",
        ["company.companyName", "registrations[0]"],
    )
    annual_report = evidence(
        "Example Build Systems 2025 annual report",
        "https://example.com/investors/annual-report-2025.pdf",
        "Example Build Systems Ltd.",
        "financial_report",
        "Pages 12, 38 and 72",
        "FY2025 revenue was AUD 185 million and net profit was AUD 14.2 million.",
        "Synthetic audited financial evidence for field placement only.",
        ["company.companyScale", "financialRecords", "assessment.payment_capacity"],
    )
    capital_source = evidence(
        "Example Build Systems 2025 equity note",
        "https://example.com/investors/annual-report-2025-equity-note.pdf",
        "Example Build Systems Ltd.",
        "financial_report",
        "Note 18 — Contributed equity",
        "Issued and fully paid ordinary share capital was AUD 25 million at 31 December 2025.",
        "Synthetic capital evidence isolated from operating-performance observations.",
        ["capitalRecords"],
    )
    customer_relation = project_evidence(
        "Project team and procurement",
        "Example Developments appointed Example Build Systems to deliver Harbour Residence.",
        "Supports the named customer relationship and active procurement window.",
        ["projects[0].participants", "relationships[0]", "competitorCustomerPortfolio"],
    )
    product_source = evidence(
        "Example Aluminum Formwork product page",
        "https://example.com/products/aluminum-formwork",
        "Example Build Systems Ltd.",
        "official_website",
        "Product, manufacturing and factory section",
        "The company owns the EX-Alu brand and manufactures panels at its Newcastle factory.",
        "Supports overlapping product, brand control and own-factory manufacturing.",
        ["productsAndServices[0]", "researchClassifications.competitor"],
    )
    inquiry_source = inquiry_evidence(
        "Inquiry body and Attachment A",
        "The buyer requests aluminum formwork for 28 repeated floors, 12,600 m², CIF Sydney.",
        "Supports the buyer-stated requirement, not legal identity or payment capacity.",
        ["inquiries[0]", "inquiryAssessment"],
    )

    data: dict[str, Any] = {
        "company": {
            "companyName": "Example Build Systems Ltd.",
            "entityType": "operating_company",
            "country": "Australia",
            "countryCode": "AU",
            "status": "active",
            "summary": "Synthetic Australian contractor and aluminum-formwork system owner used only as a complete reference fixture.",
            "researchConclusion": "Strong identity, owned product system, manufacturing, active project demand and one verified customer relationship are demonstrated by synthetic sources.",
            "foundedOn": "2012-04-18",
            "companyScale": "medium",
            "headcount": 180,
            "listingStatus": "self_listed",
            "listingDetails": "Synthetic listing on the Example Securities Exchange under ticker EBS.",
            "marketPosition": "Regional main contractor and specialist aluminum-formwork supplier.",
            "priority": "high",
            "procurementBoundary": "Project teams recommend temporary-works suppliers; head office approves framework suppliers and payment terms.",
            "evidence": [registry, annual_report],
        },
        "aliases": [{
            "name": "EBS Formwork",
            "aliasType": "trading_name",
            "language": "en-AU",
            "status": "current",
            "description": "Commercial name used for the formwork product business.",
            "note": "Not a separate legal entity.",
            "evidence": [official("Trading names", "EBS Formwork is listed as a trading name.", "Alias and entity boundary.", ["aliases[0]"])],
        }],
        "registrations": [{
            "registrationType": "company_number",
            "registrationNumber": "123456789",
            "legalName": "Example Build Systems Ltd.",
            "entityKind": "operating_company",
            "jurisdiction": "AU",
            "issuingAuthority": "Example Corporate Registry",
            "registeredOn": "2012-04-18",
            "issueDateRaw": "18 April 2012",
            "status": "active",
            "verificationStatus": "verified",
            "description": "Primary synthetic company registration.",
            "registeredBusinessScope": "Construction contracting, formwork design, manufacturing, sales and rental.",
            "expiresOn": "2099-12-31",
            "evidence": [registry],
        }],
        "capitalRecords": [
            {
                "capitalType": "registered_capital",
                "amount": 25000000,
                "currency": "AUD",
                "asOf": "2025-12-31",
                "status": "verified",
                "description": "Issued share capital reported in the synthetic audited statement.",
                "evidence": [capital_source],
            },
            {
                "capitalType": "paid_in_capital",
                "amount": 25000000,
                "currency": "AUD",
                "asOf": "2025-12-31",
                "status": "verified",
                "description": "Synthetic paid-in capital separately recorded from registered capital.",
                "evidence": [capital_source],
            },
        ],
        "websites": [{
            "url": "https://example.com",
            "websiteType": "official",
            "status": "active",
            "verificationStatus": "verified",
            "lastCheckedOn": AS_OF,
            "evidence": [official("Website footer", "Example Build Systems Ltd. and registration 123456789.", "Domain-to-entity binding.", ["websites[0]"])],
        }],
        "addresses": [{
            "addressType": "headquarters",
            "fullAddress": "100 Example Street, Sydney NSW 2000, Australia",
            "addressLine": "Level 8, 100 Example Street",
            "street": "100 Example Street",
            "city": "Sydney",
            "state": "New South Wales",
            "province": "New South Wales",
            "region": "Oceania",
            "postalCode": "2000",
            "country": "Australia",
            "status": "verified",
            "note": "Synthetic registered head office.",
            "evidence": [registry],
        }],
        "marketPresence": [{
            "presenceType": "office_and_factory",
            "country": "Australia",
            "region": "New South Wales",
            "city": "Newcastle",
            "status": "confirmed",
            "description": "Sales office and owned aluminum-formwork factory serving Australia and New Zealand.",
            "evidence": [product_source],
        }],
        "socialChannels": [{
            "platform": "LinkedIn",
            "handle": "example-build-systems",
            "url": "https://www.linkedin.com/company/example-build-systems",
            "status": "active",
            "lastCheckedOn": AS_OF,
            "lastActivityOn": "2026-08-18",
            "evidence": [evidence("Example Build Systems LinkedIn page", "https://www.linkedin.com/company/example-build-systems", "Example Build Systems Ltd.", "social_media", "About", "Company profile links to example.com.", "Synthetic social-channel binding.", ["socialChannels[0]"])],
        }],
        "researchClassifications": [
            {
                "classification": "lead",
                "status": "confirmed",
                "country": "Australia",
                "productScope": ["aluminum_formwork", "climbing_formwork"],
                "reason": "The company is a verified contractor with an active repeated-floor project and an identified procurement route.",
                "evidence": [customer_relation, inquiry_source],
            },
            {
                "classification": "competitor",
                "status": "confirmed",
                "country": "Australia",
                "productScope": ["aluminum_formwork", "formwork_rental"],
                "reason": "Owned brand, own-factory manufacturing, direct sales and rental establish product and channel competition.",
                "evidence": [product_source],
            },
        ],
        "companyRoles": [
            {
                "role": "main_contractor",
                "scope": "High-rise residential construction",
                "country": "Australia",
                "projectName": "Harbour Residence",
                "status": "confirmed",
                "rationale": "The official project page names the company as main contractor.",
                "evidence": [customer_relation],
            },
            {
                "role": "distributor_trading",
                "scope": "Direct sale and rental of its own aluminum-formwork system",
                "country": "Australia",
                "projectName": "Harbour Residence",
                "status": "confirmed",
                "rationale": "The product page states direct commercial control and rental availability.",
                "evidence": [product_source],
            },
        ],
        "productsAndServices": [{
            "name": "EX-Alu Aluminum Formwork System",
            "systemName": "EX-Alu VMC 600",
            "type": "product",
            "category": "aluminum_formwork",
            "description": "Owned modular aluminum-formwork system sold, rented, designed and supported by the company.",
            "technologyTerms": ["aluminum formwork", "monolithic casting", "VMC", "early stripping"],
            "applications": ["high-rise residential", "standard floors", "concrete walls and slabs"],
            "targetCustomers": ["developers", "main contractors", "concrete subcontractors"],
            "markets": ["Australia", "New Zealand"],
            "commercialRoles": ["manufacturer", "system_owner", "brand_owner", "rental_provider"],
            "manufacturingStatus": "own_factory_confirmed",
            "manufacturingDescription": "Panels and accessories are fabricated at the synthetic Newcastle factory; selected fasteners are sourced externally.",
            "factoryLocations": ["Newcastle, New South Wales, Australia"],
            "media": [{
                "url": "https://example.com/media/ex-alu-line.jpg",
                "mediaType": "image",
                "caption": "Synthetic EX-Alu panel production line.",
                "lastVerifiedOn": AS_OF,
                "evidence": [product_source],
            }],
            "representativeProject": "Harbour Residence",
            "status": "confirmed",
            "getoRelevance": "high",
            "evidence": [product_source],
        }],
        "projects": [{
            "projectName": "Harbour Residence",
            "aliases": ["Harbour Residences", "Project HR-28"],
            "projectType": "high_rise_residential",
            "country": "Australia",
            "region": "New South Wales",
            "city": "Sydney",
            "location": "Barangaroo precinct",
            "address": "25 Example Quay, Sydney NSW 2000, Australia",
            "participants": [
                {
                    "name": "Example Developments Pty Ltd.",
                    "role": "developer",
                    "identity": {
                        "entityKind": "legal_entity",
                        "jurisdiction": "AU",
                        "registrationNumber": "987654321",
                        "primaryDomain": "example-developments.test",
                        "otherLegalId": "ABN-98-765-432-100",
                    },
                    "status": "confirmed",
                    "lastVerifiedOn": AS_OF,
                    "evidence": [customer_relation],
                },
                {
                    "name": "Example Build Systems Ltd.",
                    "role": "main_contractor",
                    "identity": {
                        "entityKind": "operating_company",
                        "jurisdiction": "AU",
                        "registrationNumber": "123456789",
                        "primaryDomain": "example.com",
                        "otherLegalId": "ABN-12-345-678-900",
                    },
                    "status": "confirmed",
                    "lastVerifiedOn": AS_OF,
                    "evidence": [customer_relation],
                },
                {
                    "name": "Example Structures Consulting Pty Ltd.",
                    "role": "consultant",
                    "identity": {
                        "entityKind": "legal_entity",
                        "jurisdiction": "AU",
                        "registrationNumber": "456789123",
                        "primaryDomain": "example-structures.test",
                        "otherLegalId": "ABN-45-678-912-300",
                    },
                    "status": "confirmed",
                    "lastVerifiedOn": AS_OF,
                    "evidence": [project_evidence("Consultant", "Structural consultant: Example Structures Consulting.", "Consultant participation.", ["projects[0].participants[2]"])],
                },
            ],
            "targetCompanyRole": "main_contractor_and_formwork_supplier",
            "contractScope": "Design-and-construct main contract plus aluminum-formwork package.",
            "contractNumber": "HR-DNC-2025-014",
            "contractValue": 148000000,
            "currency": "AUD",
            "scale": "28-storey, 210-unit reinforced-concrete residential tower",
            "buildingArea": 48600,
            "areaUnit": "m2",
            "storeys": 28,
            "units": 210,
            "status": "active",
            "procurementStage": "formwork_supplier_shortlist",
            "startedOn": "2025-02-01",
            "endedOn": "2027-12-31",
            "expectedCompletionOn": "2027-12-31",
            "currentOrHistorical": "current",
            "inquiryMatchStatus": "matched",
            "roleVerificationStatus": "verified",
            "productsOrTechnologies": ["aluminum formwork", "reinforced concrete", "BIM coordination"],
            "potentialProducts": [{
                "productName": "GETO aluminum formwork",
                "usageSummary": "Alternative supply for towers 2 and 3 with repeated standard floors.",
                "evidence": [inquiry_source],
            }],
            "demandJudgement": "confirmed_active_demand",
            "entryWindow": "Submit technical scheme before the 2026-09-15 shortlist deadline.",
            "opportunity": "Benchmark cycle time, panel weight and lifecycle service against the incumbent EX-Alu system.",
            "procurementBoundary": "Developer approves budget; main contractor owns technical shortlist; project commercial manager negotiates terms.",
            "knownRelationship": "Example Developments is a verified current customer of Example Build Systems for this project.",
            "getoRelevance": "high_and_time_sensitive",
            "verificationStatus": "verified",
            "lastVerifiedOn": AS_OF,
            "description": "Synthetic active project that demonstrates every project and participant field.",
            "evidence": [customer_relation, inquiry_source],
        }],
        "relationships": [{
            "relationshipType": "customer",
            "counterpartyName": "Example Developments Pty Ltd.",
            "counterpartyRole": "developer",
            "companyRole": "main_contractor_and_formwork_supplier",
            "relationshipRole": "supplier",
            "relatedPartyIdentity": {
                "jurisdiction": "AU",
                "registrationNumber": "987654321",
                "primaryDomain": "example-developments.test",
                "otherLegalId": "ABN-98-765-432-100",
            },
            "projectName": "Harbour Residence",
            "productOrService": "EX-Alu Aluminum Formwork System and design-and-construct service",
            "country": "Australia",
            "status": "confirmed",
            "cooperationModeCode": "sale_and_project_delivery",
            "cooperationDepthCode": "repeat_business",
            "relationshipStatusCode": "current",
            "buyer": "Example Developments Pty Ltd.",
            "payer": "Example Developments Pty Ltd.",
            "actualUser": "Example Build Systems project delivery team",
            "customerValueAssessment": {
                "overallScore": 82.0,
                "grade": "verified_high_value",
                "assessedOn": AS_OF,
                "evidence": [customer_relation],
            },
            "description": "Verified repeat customer relationship covering the main contract and the current formwork package.",
            "exclusivity": {
                "status": "non_exclusive",
                "scope": "Harbour Residence supplier shortlist and future Australian projects",
                "description": "The project permits alternative qualified formwork suppliers.",
                "lastVerifiedOn": AS_OF,
                "evidence": [inquiry_source],
            },
            "startedOn": "2023-05-10",
            "endedOn": "2027-12-31",
            "firstEvidenceOn": "2023-05-10",
            "lastVerifiedOn": AS_OF,
            "reviewDecision": "verified_customer",
            "entryPoint": "Alternative supplier evaluation for towers 2 and 3.",
            "limitations": ["The buyer has not disclosed incumbent unit pricing.", "Final supplier approval remains with the joint procurement committee."],
            "entrySignalCode": "new_procurement_window",
            "entryAssessment": {
                "assessmentType": "relationship_entry",
                "status": "completed",
                "modelCode": "GETO_RELATIONSHIP_ENTRY",
                "modelVersion": "1.0",
                "score": 5,
                "rationale": "A documented new procurement window permits an alternative qualified supplier despite repeat business with the incumbent.",
                "assessedOn": AS_OF,
                "evidenceStatus": "verified",
                "gapCodes": ["incumbent_price_not_disclosed"],
                "evidence": [inquiry_source],
            },
            "evidence": [customer_relation, inquiry_source],
        }],
        "contacts": [{
            "contactType": "business",
            "name": "Alex Example",
            "jobTitle": "Commercial Director",
            "department": "Commercial and Procurement",
            "seniority": "director",
            "responsibilities": "Approves supplier shortlists, commercial terms and framework onboarding.",
            "buyingRole": "economic_buyer",
            "location": "Sydney, Australia",
            "workEmail": "alex@example.com",
            "workPhone": "+61 2 5550 0100",
            "linkedinUrl": "https://www.linkedin.com/in/alex-example",
            "otherProfileUrl": "https://example.com/team/alex-example",
            "verificationStatus": "verified",
            "lastVerifiedOn": AS_OF,
            "evidence": [official("Leadership team", "Alex Example is Commercial Director.", "Role and responsibility evidence; email deliverability is not inferred.", ["contacts[0].name", "contacts[0].jobTitle", "contacts[0].buyingRole"])],
        }],
        "licensesAndCertifications": [{
            "name": "New South Wales unrestricted commercial builder licence",
            "licenseType": "builder_license",
            "licenseNumber": "NSW-EX-204812",
            "authority": "Example NSW Building Authority",
            "holderName": "Example Build Systems Ltd.",
            "jurisdiction": "AU-NSW",
            "issuedOn": "2024-01-01",
            "expiresOn": "2027-12-31",
            "status": "active",
            "description": "Synthetic unrestricted commercial builder licence.",
            "scope": "Commercial buildings without a synthetic project-value limit.",
            "evidence": [evidence("Example licence register", "https://government.example/licenses/NSW-EX-204812", "Example NSW Building Authority", "government", "Licence NSW-EX-204812", "Licence is active through 2027-12-31.", "Licence and expiry verification.", ["licensesAndCertifications[0]"])],
        }],
        "financialRecords": [
            {
                "recordType": "revenue",
                "subjectEntity": "Example Build Systems Ltd.",
                "scope": "standalone",
                "accountingScope": "consolidated",
                "relationshipToTarget": "target_entity",
                "financialScope": "consolidated",
                "period": "FY2025",
                "value": 185000000,
                "currency": "AUD",
                "unit": "currency_units",
                "valueStatus": "audited",
                "description": "Synthetic consolidated revenue.",
                "evidence": [annual_report],
            },
            {
                "recordType": "net_profit",
                "subjectEntity": "Example Build Systems Ltd.",
                "scope": "standalone",
                "accountingScope": "consolidated",
                "relationshipToTarget": "target_entity",
                "financialScope": "consolidated",
                "period": "FY2025",
                "value": 14200000,
                "currency": "AUD",
                "unit": "currency_units",
                "valueStatus": "audited",
                "description": "Synthetic consolidated net profit after tax.",
                "evidence": [annual_report],
            },
        ],
        "newsAndSocialMedia": [{
            "itemType": "company_news",
            "title": "Example Build Systems wins Harbour Residence contract",
            "summary": "Synthetic announcement confirms contract award, scope and delivery schedule.",
            "publisherOrPlatform": "Example Build Systems Ltd.",
            "url": "https://example.com/news/harbour-residence-award",
            "publishedOn": "2025-02-01",
            "status": "verified",
            "relatedProject": "Harbour Residence",
            "businessMeaning": "Confirms delivery backlog and the customer relationship.",
            "evidence": [project_evidence("Contract award", "The company was awarded the Harbour Residence main contract.", "Award announcement.", ["newsAndSocialMedia[0]"])],
        }],
        "customsTransactions": [{
            "resultType": "shipment_summary",
            "direction": "import",
            "importer": "Example Build Systems Ltd.",
            "exporter": "Example Fasteners Manufacturing Co.",
            "partnerCountry": "China",
            "transactionOn": "2026-06-18",
            "dateRange": "2026-01-01/2026-06-30",
            "hsCode": "731815",
            "productDescription": "Steel fasteners for reusable formwork systems",
            "quantity": 18500,
            "quantityUnit": "kg",
            "value": 96200,
            "currency": "USD",
            "ports": ["Port of Shanghai", "Port Botany"],
            "recordCount": 3,
            "provider": "Synthetic Customs Provider",
            "queryScope": "Exact legal name plus AU country filter",
            "verificationStatus": "matched_by_strong_identity",
            "notes": "Supports imported component sourcing; does not refute own-factory panel manufacturing.",
            "evidence": [evidence("Synthetic customs result", "https://provider.example/customs/example-build-systems", "Synthetic Customs Provider", "provider", "Exact-name shipment group", "Three shipments of steel fasteners matched the verified legal name.", "Provider observation accepted only for shipment fields.", ["customsTransactions[0]"])],
        }],
        "lawsuitsAndCompliance": [{
            "recordType": "court_case",
            "caseNumber": "NSWSC-2025-EX-104",
            "authority": "Example Supreme Court of New South Wales",
            "jurisdiction": "AU-NSW",
            "recordOn": "2025-11-12",
            "status": "closed_settled",
            "adverse": False,
            "description": "Synthetic payment dispute settled without an adverse judgment.",
            "parties": ["Example Build Systems Ltd.", "Example Materials Pty Ltd."],
            "outcome": "Settlement recorded and proceeding closed.",
            "amount": 420000,
            "currency": "AUD",
            "relatedProject": "Example Civic Centre",
            "evidence": [evidence("Synthetic court register", "https://court.example/cases/NSWSC-2025-EX-104", "Example Supreme Court of New South Wales", "court", "Docket outcome", "Matter closed following settlement; no adverse judgment recorded.", "Case status and non-adverse outcome.", ["lawsuitsAndCompliance[0]"])],
        }],
        "inquiries": [{
            "inquiryRef": "WEB-2026-001",
            "inquiryNumber": "INQ-AU-2026-0818",
            "receivedOn": "2026-08-18",
            "buyerName": "Alex Example",
            "buyerContact": "alex@example.com; +61 2 5550 0100",
            "buyerRole": "Commercial Director",
            "requestedProduct": "GETO aluminum formwork system",
            "quantity": 12600,
            "quantityUnit": "m2",
            "technicalRequirements": "28 repeated floors, 3.0 m floor height, monolithic wall-slab casting, six-day cycle target.",
            "projectName": "Harbour Residence",
            "projectCountry": "Australia",
            "deliveryDestination": "Sydney project site",
            "deliveryPort": "Port Botany",
            "incoterm": "CIF Sydney",
            "signingEntity": "Example Build Systems Ltd.",
            "payer": "Example Developments Pty Ltd. subject to final contract confirmation",
            "paymentTerms": "20% advance, 70% before shipment, 10% after site acceptance; buyer requests negotiation.",
            "requestedDocuments": ["technical proposal", "cycle-time plan", "quotation", "factory QA certificate"],
            "attachments": ["WEB-2026-001-Attachment-A.pdf", "Harbour-Residence-Typical-Floor.dwg"],
            "verificationStatus": "partially_verified",
            "openQuestions": ["Confirm final payer and signing entity.", "Confirm crane capacity and floor zoning.", "Confirm whether panels are purchased or rented."],
            "evidence": [inquiry_source],
        }],
        "risks": [{
            "riskType": "commercial_and_competitive",
            "severity": "medium",
            "status": "open_with_mitigation",
            "description": "The target owns a competing system while also opening an alternative supplier window.",
            "impact": "Technical and commercial information could strengthen a direct competitor if shared without controls.",
            "blocking": False,
            "mitigation": "Separate project-specific supply opportunity from strategic competitor exposure and protect technical pricing data.",
            "evidence": [product_source, inquiry_source],
        }],
        "researchQueries": [{
            "topic": "official_projects_and_identity",
            "channel": "web_and_registry",
            "query": "Example Build Systems 123456789 Harbour Residence aluminum formwork",
            "scope": "Identity, project, product, manufacturing and customer relationship",
            "status": "found",
            "checkedOn": AS_OF,
            "resultCount": 6,
            "evidence": [registry, customer_relation, product_source],
        }],
        "assessment": {
            "assessmentType": "lead_value",
            "status": "completed",
            "modelCode": "GETO_LEAD_VALUE",
            "modelVersion": "2026-07-29",
            "ratingScaleVersion": "value-status-2026-07-29",
            "capabilityContext": {
                "foundationKey": "geto:capability-foundation",
                "foundationVersion": "2026-08-19",
                "asOf": AS_OF,
                "status": "available",
                "contentHash": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "productCodes": ["aluminum_formwork"],
                "scenarioCodes": ["high_rise_core_and_standard_floor"],
                "roleCodes": ["main_contractor"],
                "caseKeys": ["case:synthetic-harbour-residence"],
                "gapCodes": ["synthetic_reference_fixture"],
            },
            "grade": "verified_high_value",
            "overallScore": 79,
            "informationCompleteness": 92.5,
            "overallConclusion": "High-value lead with verified demand and procurement access; protect information because the same entity is also a confirmed competitor.",
            "assessedOn": AS_OF,
            "dimensions": [
                dimension("project_city_value", "项目及城市价值", 13, 12, 13, 15, "high", "Active Sydney high-rise project with repeated floors.", customer_relation, "contract_value_subject_to_final_contract", "no_overall_cap"),
                dimension("account_scale", "客户规模", 17, 15, 17, 20, "high", "Audited revenue and headcount support a medium-to-large account.", annual_report, "subsidiary_breakdown_not_published", "no_overall_cap"),
                dimension("future_project_demand", "未来项目需求", 16, 14, 16, 20, "high", "Inquiry and shortlist deadline confirm near-term demand.", inquiry_source, "follow_on_pipeline_not_verified", "no_overall_cap"),
                dimension("reachability", "可触达性", 8, 7, 8, 10, "high", "Named commercial director and direct business channels are verified.", official("Leadership team", "Alex Example is Commercial Director.", "Current role and direct route.", ["assessment.reachability"]), "delegated_authority_limit_not_published", "no_overall_cap"),
                dimension("payment_capacity", "付款能力", 12, 11, 12, 15, "medium_high", "Audited profitability supports capacity, while project payment allocation still requires confirmation.", annual_report, "project_payer_allocation_pending", "no_overall_cap"),
                dimension("multi_product_fit", "多产品适配", 13, 12, 13, 20, "medium_high", "Project geometry fits aluminum formwork and climbing solutions, but competitor status narrows the safe offering.", product_source, "climbing_scope_not_yet_designed", "no_overall_cap"),
            ],
            "capCodes": ["competitive_information_boundary"],
            "gapCodes": ["final_payer_confirmation", "incumbent_price_not_disclosed"],
            "cohortKey": "AU:main_contractor",
            "cohortBaselineVersion": "AU:main_contractor:2026-08-20:sha256:bbbbbbbbbbbbbbbb",
            "cohortAsOf": AS_OF,
            "evidence": [registry, annual_report, customer_relation, inquiry_source],
        },
        "inquiryAssessment": {
            "assessmentType": "inquiry_readiness",
            "status": "completed",
            "modelCode": "GETO_INQUIRY_READINESS",
            "modelVersion": "2026-08-19",
            "inquiryRef": "WEB-2026-001",
            "grade": "qualified_needs_clarification",
            "overallScore": 72,
            "overallConclusion": "Requirements and project are credible enough for a controlled quotation after confirming payer, signing entity and commercial safeguards.",
            "assessedOn": AS_OF,
            "dimensions": [
                inquiry_dimension("identity_confidence", "主体可信度", 13, 15, "Registry and official domain bind the operating company.", registry, "beneficial_owner_not_in_fixture"),
                inquiry_dimension("requirement_specificity", "需求明确度", 17, 20, "Product, area, cycle target and drawings are provided.", inquiry_source, "panel_breakdown_pending"),
                inquiry_dimension("project_readiness", "项目成熟度", 16, 20, "Project and shortlist deadline are verified.", customer_relation, "final_shortlist_members_not_disclosed"),
                inquiry_dimension("reachability_authority", "触达与授权", 11, 15, "Named director is reachable; delegated signing authority is not published.", official("Leadership team", "Alex Example is Commercial Director.", "Role evidence only.", ["inquiryAssessment.reachability_authority"]), "signing_authority_pending"),
                inquiry_dimension("commercial_payment_readiness", "商务与付款准备度", 7, 15, "Proposed terms exist, but final payer and terms need confirmation.", inquiry_source, "final_payer_confirmation"),
                inquiry_dimension("technical_product_fit", "技术与产品适配", 8, 15, "Repeated floors fit aluminum formwork; crane and zoning details remain open.", inquiry_source, "crane_and_zoning_pending"),
            ],
            "hardBlockCodes": ["unverified_signing_and_payer"],
            "gapCodes": ["payment_terms_require_confirmation", "technical_clarifications_open"],
        },
        "competitorCustomerPortfolio": {
            "assessmentType": "competitor_customer_portfolio",
            "status": "completed",
            "modelCode": "GETO_COMPETITOR_CUSTOMER_PORTFOLIO",
            "modelVersion": "2026-08-19",
            "customerValueModelCode": "GETO_LEAD_VALUE",
            "asOf": AS_OF,
            "verifiedCustomerCount": 1,
            "scoredCustomerCount": 1,
            "customerScoreCoverage": 1.0,
            "averageCustomerValueScore": 82.0,
            "customers": [{
                "companyName": "Example Developments Pty Ltd.",
                "country": "Australia",
                "relationshipCount": 1,
                "customerAssessmentStatus": "completed",
                "customerValueScore": 82.0,
                "customerValueModelVersion": "2026-07-29",
                "cohortBaselineVersion": "AU:developer:2026-08-20:sha256:cccccccccccccccc",
                "assessedOn": AS_OF,
                "evidence": [customer_relation],
            }],
        },
        "missingInformation": [{
            "topic": "private_project_cost_breakdown",
            "status": "limited_public_access",
            "description": "Detailed project cost plan and incumbent unit prices are private.",
            "impact": "Margin comparison and final bid strategy require buyer clarification.",
            "checkedScope": "Inquiry attachment, public project page and published financial statement.",
            "recommendedAction": "Request the buyer's package budget range and incumbent comparison basis under NDA.",
            "evidence": [inquiry_source],
        }],
        "recommendedActions": [{
            "action": "Hold a technical-commercial clarification call and issue a controlled budget quotation.",
            "priority": "high",
            "owner": "GETO Australia sales lead",
            "timing": "Before 2026-09-01",
            "reason": "The shortlist deadline is near and the buyer, payer, scope and information boundary need confirmation.",
            "rationale": "This closes the highest-impact inquiry gaps without disclosing unrestricted competitor-sensitive pricing.",
            "evidence": [inquiry_source, product_source],
        }],
        "additionalInformation": [{
            "topic": "synthetic_fixture_notice",
            "title": "Complete reference fixture",
            "details": "Every value in this file is synthetic and exists to demonstrate field placement, Evidence nesting and assessment linkage.",
            "status": "reference_only",
            "evidence": [evidence("Fixture documentation", "https://example.com/reference-fixture", "GETO Skill Maintainers", "other", "Usage notice", "This is a synthetic reference fixture and not a real company report.", "Prevents synthetic values from being treated as research facts.", ["additionalInformation[0]"])],
        }],
        "reportFiles": [
            {
                "fileName": "report.md",
                "path": "report.md",
                "format": "markdown",
                "reportType": "diligence",
                "language": "zh-CN",
                "generatedOn": AS_OF,
                "description": "Detailed synthetic company diligence report.",
            },
            {
                "fileName": "inquiry-assessment.md",
                "path": "RisksAndAssessment/inquiry-assessment.md",
                "format": "markdown",
                "reportType": "assessment",
                "language": "zh-CN",
                "generatedOn": AS_OF,
                "description": "Synthetic inquiry-readiness assessment supplement.",
            },
            {
                "fileName": "competitor-customer-portfolio.md",
                "path": "Relationships/competitor-customer-portfolio.md",
                "format": "markdown",
                "reportType": "supplement",
                "language": "zh-CN",
                "generatedOn": AS_OF,
                "description": "Synthetic verified-customer portfolio and entry assessment supplement.",
            },
        ],
        "researchStatus": "completed_with_gaps",
        "lastResearchedOn": AS_OF,
    }
    return data


def find_empty(value: Any, path: str = "$") -> list[str]:
    empty: list[str] = []
    if value is None or value == "" or value == [] or value == {}:
        empty.append(path)
    elif isinstance(value, dict):
        for key, child in value.items():
            empty.extend(find_empty(child, f"{path}.{key}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            empty.extend(find_empty(child, f"{path}[{index}]"))
    return empty


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    example = build_example()
    empty = find_empty(example)
    if empty:
        raise SystemExit("empty example values: " + ", ".join(empty))
    args.output.write_text(json.dumps(example, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
